openhab:
  container_name: openhab
  image: "openhab/openhab:2.1.0-armhf"
  restart: always
  net: host
  cap_add:
    - NET_ADMIN
    - NET_RAW
  volumes:
    - "/etc/localtime:/etc/localtime:ro"
    - "/etc/timezone:/etc/timezone:ro"
    - "openhab_conf:/openhab/conf"
    - "openhab_userdata:/openhab/userdata"
    - "openhab_addons:/openhab/addons"
  # The command node is very important. It overrides
  # the "gosu openhab ./start.sh" command from Dockerfile and runs as root!
  command: "./start.sh"

mosquitto:
  container_name: mosquitto
  image: "fstehle/rpi-mosquitto"
  restart: always
  ports:
    - "1883:1883"
    - "9001:9001"
  volumes:
    - "/srv/mosquitto/config:/mqtt/config:ro"
    - "/srv/mosquitto/data:/mqtt/data/"
